// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3824.Competition2019;

import org.usfirst.frc3824.Competition2019.commands.*;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.*;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    //// CREATING BUTTONS
    // One type of button is a joystick button which is any button on a joystick.
    // You create one by telling it which joystick it's on and which button
    // number it is.
    // Joystick stick = new Joystick(port);
    // Button button = new JoystickButton(stick, buttonNumber);

    // There are a few additional built in buttons you can use. Additionally,
    // by subclassing Button you can create custom triggers and bind those to
    // commands the same as any other Button.

    //// TRIGGERING COMMANDS WITH BUTTONS
    // Once you have a button, it's trivial to bind it to a button in one of
    // three ways:

    // Start the command when the button is pressed and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenPressed(new ExampleCommand());

    // Run the command while the button is being held down and interrupt it once
    // the button is released.
    // button.whileHeld(new ExampleCommand());

    // Start the command when the button is released  and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenReleased(new ExampleCommand());


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public JoystickButton backClimbDeploy;
    public JoystickButton backClimbRetract;
    public JoystickButton frontClimbDeploy;
    public JoystickButton frontClimbRetract;
    public JoystickButton spinShooterWheelsCargo;
    public JoystickButton stopShooterWheelsCargo;
    public JoystickButton shoot;
    public JoystickButton unshoot;
    public JoystickButton shooterAngleBackTop;
    public JoystickButton shooterAngleBackMiddle;
    public JoystickButton shooterAngleBackBottom;
    public JoystickButton shooterAngleFrontTop;
    public JoystickButton shooterAngleFrontMiddle;
    public JoystickButton shooterAngleFrontBottom;
    public Joystick joystickControl;
    public JoystickButton highGear;
    public JoystickButton lowGear;
    public Joystick joystickDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public OI() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        joystickDrive = new Joystick(0);
        
        lowGear = new JoystickButton(joystickDrive, 2);
        lowGear.whenReleased(new ChassisGearShift(false));
        highGear = new JoystickButton(joystickDrive, 2);
        highGear.whenPressed(new ChassisGearShift(true));
        joystickControl = new Joystick(1);
        
        shooterAngleFrontBottom = new JoystickButton(joystickControl, 11);
        shooterAngleFrontBottom.whenPressed(new ShooterAngleRotate(25));
        shooterAngleFrontMiddle = new JoystickButton(joystickControl, 10);
        shooterAngleFrontMiddle.whenPressed(new ShooterAngleRotate(45));
        shooterAngleFrontTop = new JoystickButton(joystickControl, 9);
        shooterAngleFrontTop.whenPressed(new ShooterAngleRotate(70));
        shooterAngleBackBottom = new JoystickButton(joystickControl, 5);
        shooterAngleBackBottom.whenPressed(new ShooterAngleRotate(160));
        shooterAngleBackMiddle = new JoystickButton(joystickControl, 2);
        shooterAngleBackMiddle.whenPressed(new ShooterAngleRotate(135));
        shooterAngleBackTop = new JoystickButton(joystickControl, 4);
        shooterAngleBackTop.whenPressed(new ShooterAngleRotate(115));
        unshoot = new JoystickButton(joystickControl, 1);
        unshoot.whenReleased(new ShooterPusherRetract());
        shoot = new JoystickButton(joystickControl, 1);
        shoot.whenPressed(new ShooterPusherExtend());
        stopShooterWheelsCargo = new JoystickButton(joystickControl, 3);
        stopShooterWheelsCargo.whenReleased(new SetShooterSpeed(0));
        spinShooterWheelsCargo = new JoystickButton(joystickControl, 3);
        spinShooterWheelsCargo.whenPressed(new SetShooterSpeed(0.75));
        frontClimbRetract = new JoystickButton(joystickControl, 6);
        frontClimbRetract.whenReleased(new FrontClimberRetract());
        frontClimbDeploy = new JoystickButton(joystickControl, 6);
        frontClimbDeploy.whenPressed(new FrontClimberExtend());
        backClimbRetract = new JoystickButton(joystickControl, 7);
        backClimbRetract.whenReleased(new BackClimberRetract());
        backClimbDeploy = new JoystickButton(joystickControl, 7);
        backClimbDeploy.whenPressed(new BackClimberExtend());


        // SmartDashboard Buttons
        SmartDashboard.putData("Autonomous Command", new AutonomousCommand());
        SmartDashboard.putData("FrontClimberExtend", new FrontClimberExtend());
        SmartDashboard.putData("FrontClimberRetract", new FrontClimberRetract());
        SmartDashboard.putData("BackClimberExtend", new BackClimberExtend());
        SmartDashboard.putData("BackClimberRetract", new BackClimberRetract());
        SmartDashboard.putData("SetPIDValues", new SetPIDValues());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public Joystick getJoystickControl() {
        return joystickControl;
    }

    public Joystick getJoystickDrive() {
        return joystickDrive;
    }


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
}

