// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3824.Competition2019.commands;

import edu.wpi.first.wpilibj.command.CommandGroup;

import org.usfirst.frc3824.Competition2019.Constants;
import org.usfirst.frc3824.Competition2019.Robot;
import org.usfirst.frc3824.Competition2019.subsystems.*;

/**
 *
 */
public class AllSystemsClimbCenter extends CommandGroup {


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
    public AllSystemsClimbCenter() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
        // Add Commands here:
        // e.g. addSequential(new Command1());
        //      addSequential(new Command2());
        // these will run in order.

        // To run multiple commands at the same time,
        // use addParallel()
        // e.g. addParallel(new Command1());
        //      addSequential(new Command2());
        // Command1 and Command2 will run in parallel.

        // A command group will require all of the subsystems that each member
        // would require.
        // e.g. if Command1 requires chassis, and Command2 requires arm,
        // a CommandGroup containing them would require both the chassis and the
        // arm.
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS

        // if (!Robot.getKillClimber()) constantly checks if climber was killed by driver

        if (!Robot.getKillClimber())
        {
            // set drive direction to correct orientation for climbing (front of robot direction)
            Robot.chassis.setDriveDirection(-1);
        }

        if (!Robot.getKillClimber())
        {
            // ensure robot intake is in start position
            addParallel(new ShooterAngleRotate(Constants.ALL_CENTER_SHOOTER_CLIMB_START_POSITION));
            // ensure robot is against platform
            addSequential(new DriveWithPower(Constants.ALL_CENTER_CHASSIS_INITIAL_POWER, 
                Constants.ALL_CENTER_CHASSIS_INITIAL_TIME), Constants.ALL_CENTER_CHASSIS_TIMEOUT);
        }
        
        // extends front and back climber at the same time
        if (!Robot.getKillClimber())
        {
            addParallel(new ClimberFrontSetPosition(Constants.ALL_CENTER_FRONT_CLIMBER_EXTEND_POSITION));
            addParallel(new ClimberBackSetPosition(Constants.ALL_CENTER_BACK_CLIMBER_EXTEND_POSITION));
            // delay only 2 seconds in order to rotate shooter angle to pull in position faster
            addSequential(new Delay(2));
        }

        // rotate shooter angle in order to pull robot onto platform
        if (!Robot.getKillClimber())
        {
            addParallel(new ShooterAngleRotate(Constants.ALL_CENTER_SHOOTER_PULL_IN_POSITION));
            addSequential(new Delay(2));
        }
        
        if (!Robot.getKillClimber())
        {
            // start shooter climber wheels in order to pull in
            addParallel(new SetShooterSpeedStraight(Constants.ALL_CENTER_SHOOTER_PULL_IN_RPM));
            // drive forward onto the platform
            addSequential(new DriveWithPower(Constants.ALL_CENTER_CHASSIS_PLATFORM_POWER, 
                Constants.ALL_CENTER_CHASSIS_PLATFORM_TIME), Constants.ALL_CENTER_CHASSIS_TIMEOUT);
        }

        // bring up back climber
        if (!Robot.getKillClimber())
        {
            addParallel(new ClimberBackSetPosition(Constants.ALL_CENTER_BACK_CLIMBER_RETRACT_POSITION));
            addSequential(new Delay(2));
        }

        // drive forward onto the platform
        if (!Robot.getKillClimber())
        {
            addSequential(new DriveWithPower(Constants.ALL_CENTER_CHASSIS_PLATFORM_POWER, 
                Constants.ALL_CENTER_CHASSIS_PLATFORM_TIME), Constants.ALL_CENTER_CHASSIS_TIMEOUT);
        }

        if (!Robot.getKillClimber())
        {
            // bring up front climber
            addParallel(new ClimberFrontSetPosition(Constants.ALL_CENTER_FRONT_CLIMBER_RETRACT_POSITION));
            addSequential(new Delay(2));
        }
        if (!Robot.getKillClimber())
        {
            // drive forward onto the platform
            addParallel(new DriveWithPower(Constants.ALL_CENTER_CHASSIS_PLATFORM_POWER, 
                Constants.ALL_CENTER_CHASSIS_PLATFORM_TIME), Constants.ALL_CENTER_CHASSIS_TIMEOUT);
            // bring shooter angle rotate to home position so it doesn't hit driver station
            addSequential(new ShooterAngleRotate(Constants.ALL_CENTER_SHOOTER_HOME_POSITION));
        }
    } 
}
