// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3824.Competition2019.commands;
import edu.wpi.first.wpilibj.command.Command;

import org.usfirst.frc3824.Competition2019.Constants;
import org.usfirst.frc3824.Competition2019.Robot;
import org.usfirst.frc3824.Competition2019.support.Limelight;

/**
 *
 */
public class AutonomousDriveToTarget extends Command {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    Limelight cam;

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public AutonomousDriveToTarget() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.chassis);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
        // set limelight to vision processing mode
        Limelight.getInstance().setCamModeVision();
        // drive to target using WPI PID controller
        Robot.chassis.driveToTargetWithCameraPID();

        // Prepare shooter if we're holding cargo
        if(Robot.getNextGamepiece() == 2)
        {
            // WHEELS: true = top wheels, false = bottom wheels
            // SHOOTER TYPE: true = spaceship, false = cargoship
            // RAW BUTTONS: 7 = top, 19 = bottom, neither = middle
            // RAW BUTTONS: 8 = front, 9 = back, neither = middle
            if (Robot.shooter.getShooterType())
            {
                if (Robot.oi.board.getRawButton(8)) // front
                {
                    if (Robot.oi.board.getRawButton(7)) // top
                    {
                        Robot.shooter.setWheelVelocity(Constants.SHOOTER_TOPWHEEL_SPACESHIP_FRONT_TOP_RPM, true);
                        Robot.shooter.setWheelVelocity(Constants.SHOOTER_BOTTOMWHEEL_SPACESHIP_FRONT_TOP_RPM, false);
                    }
                        
                    else if (Robot.oi.board.getRawButton(19)) // bottom
                    {
                        Robot.shooter.setWheelVelocity(Constants.SHOOTER_TOPWHEEL_SPACESHIP_BOTTOM_RPM, true);
                        Robot.shooter.setWheelVelocity(Constants.SHOOTER_BOTTOMWHEEL_SPACESHIP_BOTTOM_RPM, false);
                    }
                    else // middle
                    {
                        Robot.shooter.setWheelVelocity(Constants.SHOOTER_TOPWHEEL_SPACESHIP_FRONT_MIDDLE_RPM, true);
                        Robot.shooter.setWheelVelocity(Constants.SHOOTER_BOTTOMWHEEL_SPACESHIP_FRONT_MIDDLE_RPM, false);
                    }
                } 
                else if (Robot.oi.board.getRawButton(9)) // back
                {
                    if (Robot.oi.board.getRawButton(7)) // top
                    {
                        Robot.shooter.setWheelVelocity(Constants.SHOOTER_TOPWHEEL_SPACESHIP_BACK_TOP_RPM, true);
                        Robot.shooter.setWheelVelocity(Constants.SHOOTER_BOTTOMWHEEL_SPACESHIP_BACK_TOP_RPM, false);
                    }
                        
                    else if (Robot.oi.board.getRawButton(19)) // bottom
                    {
                        Robot.shooter.setWheelVelocity(Constants.SHOOTER_TOPWHEEL_SPACESHIP_BOTTOM_RPM, true);
                        Robot.shooter.setWheelVelocity(Constants.SHOOTER_BOTTOMWHEEL_SPACESHIP_BOTTOM_RPM, false);
                    }
                    else // middle
                    {
                        Robot.shooter.setWheelVelocity(Constants.SHOOTER_TOPWHEEL_SPACESHIP_BACK_MIDDLE_RPM, true);
                        Robot.shooter.setWheelVelocity(Constants.SHOOTER_BOTTOMWHEEL_SPACESHIP_BACK_MIDDLE_RPM, false);
                    }
                }
            }
            else
            {
                if (Robot.oi.board.getRawButton(8)) // front
                {
                    Robot.shooter.setWheelVelocity(Constants.SHOOTER_TOPWHEEL_CARGOSHIP_FRONT_RPM, true);
                    Robot.shooter.setWheelVelocity(Constants.SHOOTER_BOTTOMWHEEL_CARGOSHIP_FRONT_RPM, false);
                }
                else if (Robot.oi.board.getRawButton(9)) // back
                {
                    Robot.shooter.setWheelVelocity(Constants.SHOOTER_TOPWHEEL_CARGOSHIP_BACK_RPM, true);
                    Robot.shooter.setWheelVelocity(Constants.SHOOTER_BOTTOMWHEEL_CARGOSHIP_BACK_RPM, false);
                }
            }
        }
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        if (Robot.oi.joystickDrive.getRawButton(Constants.DRIVE_TO_TARGET_BUTTON))
            return false;
        else
            return true;
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
        Robot.chassis.resetChassisPIDcontrollers();
        Limelight.getInstance().restoreLastCamMode();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
        end();
    }
}
